# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdministrarCursos-IGU.ui'
#
# Created: Tue May 12 10:32:48 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class VentanaAdministrarCursos(QtGui.QFrame):
    def __init__(self):
        super(VentanaAdministrarCursos, self).__init__()
        self.setupUi(self)

    def setupUi(self, VentanaAdministrarCursos):
        VentanaAdministrarCursos.setObjectName(_fromUtf8("VentanaAdministrarCursos"))
        VentanaAdministrarCursos.resize(554, 370)
        self.tabWidget = QtGui.QTabWidget(VentanaAdministrarCursos)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 551, 291))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Buscar = QtGui.QWidget()
        self.Buscar.setObjectName(_fromUtf8("Buscar"))
        self.botonBuscarCurso = QtGui.QPushButton(self.Buscar)
        self.botonBuscarCurso.setGeometry(QtCore.QRect(30, 180, 98, 27))
        self.botonBuscarCurso.setObjectName(_fromUtf8("botonBuscarCurso"))
        self.campoBuscarIdCurso = QtGui.QLineEdit(self.Buscar)
        self.campoBuscarIdCurso.setGeometry(QtCore.QRect(110, 20, 113, 27))
        self.campoBuscarIdCurso.setObjectName(_fromUtf8("campoBuscarIdCurso"))
        self.etiquetaBuscarIdCurso = QtGui.QLabel(self.Buscar)
        self.etiquetaBuscarIdCurso.setGeometry(QtCore.QRect(20, 30, 66, 17))
        self.etiquetaBuscarIdCurso.setObjectName(_fromUtf8("etiquetaBuscarIdCurso"))
        self.etiquetaBuscarDescripcionCurso = QtGui.QLabel(self.Buscar)
        self.etiquetaBuscarDescripcionCurso.setGeometry(QtCore.QRect(20, 60, 91, 17))
        self.etiquetaBuscarDescripcionCurso.setObjectName(_fromUtf8("etiquetaBuscarDescripcionCurso"))
        self.etiquetaBuscarInicioCurso = QtGui.QLabel(self.Buscar)
        self.etiquetaBuscarInicioCurso.setGeometry(QtCore.QRect(20, 90, 66, 17))
        self.etiquetaBuscarInicioCurso.setObjectName(_fromUtf8("etiquetaBuscarInicioCurso"))
        self.etiquetaBuscarFinCurso = QtGui.QLabel(self.Buscar)
        self.etiquetaBuscarFinCurso.setGeometry(QtCore.QRect(20, 120, 66, 17))
        self.etiquetaBuscarFinCurso.setObjectName(_fromUtf8("etiquetaBuscarFinCurso"))
        self.botonBuscarLimparCurso = QtGui.QPushButton(self.Buscar)
        self.botonBuscarLimparCurso.setGeometry(QtCore.QRect(20, 210, 131, 27))
        self.botonBuscarLimparCurso.setObjectName(_fromUtf8("botonBuscarLimparCurso"))
        self.campoBuscarDescripcionCurso = QtGui.QLineEdit(self.Buscar)
        self.campoBuscarDescripcionCurso.setGeometry(QtCore.QRect(110, 50, 113, 27))
        self.campoBuscarDescripcionCurso.setObjectName(_fromUtf8("campoBuscarDescripcionCurso"))
        self.campoBuscarInicioCurso = QtGui.QLineEdit(self.Buscar)
        self.campoBuscarInicioCurso.setGeometry(QtCore.QRect(110, 80, 113, 27))
        self.campoBuscarInicioCurso.setObjectName(_fromUtf8("campoBuscarInicioCurso"))
        self.campoBuscarFinCurso = QtGui.QLineEdit(self.Buscar)
        self.campoBuscarFinCurso.setGeometry(QtCore.QRect(110, 110, 113, 27))
        self.campoBuscarFinCurso.setObjectName(_fromUtf8("campoBuscarFinCurso"))
        self.etiquetaBuscarActividadesCurso = QtGui.QLabel(self.Buscar)
        self.etiquetaBuscarActividadesCurso.setGeometry(QtCore.QRect(260, 30, 161, 17))
        self.etiquetaBuscarActividadesCurso.setObjectName(_fromUtf8("etiquetaBuscarActividadesCurso"))
        self.listaBuscarActividadescurso = QtGui.QListWidget(self.Buscar)
        self.listaBuscarActividadescurso.setGeometry(QtCore.QRect(260, 50, 256, 192))
        self.listaBuscarActividadescurso.setObjectName(_fromUtf8("listaBuscarActividadescurso"))
        self.tabWidget.addTab(self.Buscar, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.campoBorrarCurso = QtGui.QLineEdit(self.tab_2)
        self.campoBorrarCurso.setGeometry(QtCore.QRect(90, 40, 113, 27))
        self.campoBorrarCurso.setObjectName(_fromUtf8("campoBorrarCurso"))
        self.etiquetaBorrarCurso = QtGui.QLabel(self.tab_2)
        self.etiquetaBorrarCurso.setGeometry(QtCore.QRect(20, 50, 66, 17))
        self.etiquetaBorrarCurso.setObjectName(_fromUtf8("etiquetaBorrarCurso"))
        self.BotonBorrarCurso = QtGui.QPushButton(self.tab_2)
        self.BotonBorrarCurso.setGeometry(QtCore.QRect(240, 40, 98, 27))
        self.BotonBorrarCurso.setObjectName(_fromUtf8("BotonBorrarCurso"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.campoCrearIdCurso = QtGui.QLineEdit(self.tab_3)
        self.campoCrearIdCurso.setGeometry(QtCore.QRect(200, 40, 113, 27))
        self.campoCrearIdCurso.setObjectName(_fromUtf8("campoCrearIdCurso"))
        self.campoCrearDescripcionCurso = QtGui.QLineEdit(self.tab_3)
        self.campoCrearDescripcionCurso.setGeometry(QtCore.QRect(200, 70, 113, 27))
        self.campoCrearDescripcionCurso.setObjectName(_fromUtf8("campoCrearDescripcionCurso"))
        self.etiquetaCrearIdCurso = QtGui.QLabel(self.tab_3)
        self.etiquetaCrearIdCurso.setGeometry(QtCore.QRect(40, 40, 66, 17))
        self.etiquetaCrearIdCurso.setObjectName(_fromUtf8("etiquetaCrearIdCurso"))
        self.etiquetaCrearDescripcionCurso = QtGui.QLabel(self.tab_3)
        self.etiquetaCrearDescripcionCurso.setGeometry(QtCore.QRect(40, 70, 91, 17))
        self.etiquetaCrearDescripcionCurso.setObjectName(_fromUtf8("etiquetaCrearDescripcionCurso"))
        self.etiquetaCrearInicioCurso = QtGui.QLabel(self.tab_3)
        self.etiquetaCrearInicioCurso.setGeometry(QtCore.QRect(40, 110, 66, 17))
        self.etiquetaCrearInicioCurso.setObjectName(_fromUtf8("etiquetaCrearInicioCurso"))
        self.etiquetaCrearFinCurso = QtGui.QLabel(self.tab_3)
        self.etiquetaCrearFinCurso.setGeometry(QtCore.QRect(40, 140, 66, 17))
        self.etiquetaCrearFinCurso.setObjectName(_fromUtf8("etiquetaCrearFinCurso"))
        self.campoCrearInicioCurso = QtGui.QDateEdit(self.tab_3)
        self.campoCrearInicioCurso.setGeometry(QtCore.QRect(200, 100, 110, 27))
        self.campoCrearInicioCurso.setObjectName(_fromUtf8("campoCrearInicioCurso"))
        self.campoCrearFinCurso = QtGui.QDateEdit(self.tab_3)
        self.campoCrearFinCurso.setGeometry(QtCore.QRect(200, 130, 110, 27))
        self.campoCrearFinCurso.setObjectName(_fromUtf8("campoCrearFinCurso"))
        self.campoCrearActividadCurso = QtGui.QLineEdit(self.tab_3)
        self.campoCrearActividadCurso.setGeometry(QtCore.QRect(200, 160, 113, 27))
        self.campoCrearActividadCurso.setObjectName(_fromUtf8("campoCrearActividadCurso"))
        self.etiquetaCrearActividadCurso = QtGui.QLabel(self.tab_3)
        self.etiquetaCrearActividadCurso.setGeometry(QtCore.QRect(40, 170, 131, 17))
        self.etiquetaCrearActividadCurso.setObjectName(_fromUtf8("etiquetaCrearActividadCurso"))
        self.botonCrearAgregarActividadCurso = QtGui.QPushButton(self.tab_3)
        self.botonCrearAgregarActividadCurso.setGeometry(QtCore.QRect(330, 160, 81, 27))
        self.botonCrearAgregarActividadCurso.setObjectName(_fromUtf8("botonCrearAgregarActividadCurso"))
        self.botonCrearCurso = QtGui.QPushButton(self.tab_3)
        self.botonCrearCurso.setGeometry(QtCore.QRect(80, 220, 98, 27))
        self.botonCrearCurso.setObjectName(_fromUtf8("botonCrearCurso"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.campoEditarIdcurso = QtGui.QLineEdit(self.tab)
        self.campoEditarIdcurso.setGeometry(QtCore.QRect(170, 40, 113, 27))
        self.campoEditarIdcurso.setObjectName(_fromUtf8("campoEditarIdcurso"))
        self.campoEditardescripcioncurso = QtGui.QLineEdit(self.tab)
        self.campoEditardescripcioncurso.setGeometry(QtCore.QRect(170, 70, 113, 27))
        self.campoEditardescripcioncurso.setObjectName(_fromUtf8("campoEditardescripcioncurso"))
        self.campoEditarActividadcurso = QtGui.QLineEdit(self.tab)
        self.campoEditarActividadcurso.setGeometry(QtCore.QRect(170, 160, 113, 27))
        self.campoEditarActividadcurso.setObjectName(_fromUtf8("campoEditarActividadcurso"))
        self.campoEditarFincurso = QtGui.QDateEdit(self.tab)
        self.campoEditarFincurso.setGeometry(QtCore.QRect(170, 130, 110, 27))
        self.campoEditarFincurso.setObjectName(_fromUtf8("campoEditarFincurso"))
        self.campoEditarIniciocurso = QtGui.QDateEdit(self.tab)
        self.campoEditarIniciocurso.setGeometry(QtCore.QRect(170, 100, 110, 27))
        self.campoEditarIniciocurso.setObjectName(_fromUtf8("campoEditarIniciocurso"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 50, 66, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(30, 80, 91, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(30, 110, 66, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(30, 140, 66, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 170, 131, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.botonEditarAgregarActividadCurso = QtGui.QPushButton(self.tab)
        self.botonEditarAgregarActividadCurso.setGeometry(QtCore.QRect(310, 160, 81, 27))
        self.botonEditarAgregarActividadCurso.setObjectName(_fromUtf8("botonEditarAgregarActividadCurso"))
        self.botonEditarCurso = QtGui.QPushButton(self.tab)
        self.botonEditarCurso.setGeometry(QtCore.QRect(110, 210, 98, 27))
        self.botonEditarCurso.setObjectName(_fromUtf8("botonEditarCurso"))
        self.botonEditarQuitarActividadCurso = QtGui.QPushButton(self.tab)
        self.botonEditarQuitarActividadCurso.setGeometry(QtCore.QRect(400, 160, 98, 27))
        self.botonEditarQuitarActividadCurso.setObjectName(_fromUtf8("botonEditarQuitarActividadCurso"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(VentanaAdministrarCursos)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(VentanaAdministrarCursos)

    def retranslateUi(self, VentanaAdministrarCursos):
        VentanaAdministrarCursos.setWindowTitle(_translate("VentanaAdministrarCursos", "Form", None))
        self.botonBuscarCurso.setText(_translate("VentanaAdministrarCursos", "Buscar", None))
        self.etiquetaBuscarIdCurso.setText(_translate("VentanaAdministrarCursos", "ID", None))
        self.etiquetaBuscarDescripcionCurso.setText(_translate("VentanaAdministrarCursos", "Descripcion", None))
        self.etiquetaBuscarInicioCurso.setText(_translate("VentanaAdministrarCursos", "Inicio", None))
        self.etiquetaBuscarFinCurso.setText(_translate("VentanaAdministrarCursos", "Fin", None))
        self.botonBuscarLimparCurso.setText(_translate("VentanaAdministrarCursos", "Limpiar campos", None))
        self.etiquetaBuscarActividadesCurso.setText(_translate("VentanaAdministrarCursos", "Nombre Actividadades", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Buscar), _translate("VentanaAdministrarCursos", "Buscar", None))
        self.etiquetaBorrarCurso.setText(_translate("VentanaAdministrarCursos", "ID", None))
        self.BotonBorrarCurso.setText(_translate("VentanaAdministrarCursos", "Borrar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("VentanaAdministrarCursos", "Borrar", None))
        self.etiquetaCrearIdCurso.setText(_translate("VentanaAdministrarCursos", "ID", None))
        self.etiquetaCrearDescripcionCurso.setText(_translate("VentanaAdministrarCursos", "Descripcion", None))
        self.etiquetaCrearInicioCurso.setText(_translate("VentanaAdministrarCursos", "Inicio", None))
        self.etiquetaCrearFinCurso.setText(_translate("VentanaAdministrarCursos", "Fin", None))
        self.etiquetaCrearActividadCurso.setText(_translate("VentanaAdministrarCursos", "Nombre Actividad", None))
        self.botonCrearAgregarActividadCurso.setText(_translate("VentanaAdministrarCursos", "Agregar", None))
        self.botonCrearCurso.setText(_translate("VentanaAdministrarCursos", "Crear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("VentanaAdministrarCursos", "Crear", None))
        self.label_7.setText(_translate("VentanaAdministrarCursos", "ID", None))
        self.label_8.setText(_translate("VentanaAdministrarCursos", "Descripcion", None))
        self.label_9.setText(_translate("VentanaAdministrarCursos", "Inicio", None))
        self.label_10.setText(_translate("VentanaAdministrarCursos", "Fin", None))
        self.label_11.setText(_translate("VentanaAdministrarCursos", "Nombre Actividad", None))
        self.botonEditarAgregarActividadCurso.setText(_translate("VentanaAdministrarCursos", "Agregar", None))
        self.botonEditarCurso.setText(_translate("VentanaAdministrarCursos", "Editar", None))
        self.botonEditarQuitarActividadCurso.setText(_translate("VentanaAdministrarCursos", "Quitar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VentanaAdministrarCursos", "Editar", None))
        
		
if __name__  == "__main__":
    app = QtGui.QApplication(sys.argv)
    w = VentanaAdministrarCursos()
    w.show()
    sys.exit(app.exec_())


